# Generated by Django 5.1.1 on 2024-10-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('user_id', models.IntegerField()),
                ('num_right_answers', models.IntegerField()),
                ('num_wrong_answers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_id', models.CharField(blank=True, max_length=200)),
                ('poll_question', models.CharField(blank=True, max_length=200)),
                ('poll_right_asnwer', models.CharField(blank=True, max_length=200)),
                ('poll_right_asnwer_id', models.IntegerField()),
                ('date_create', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, max_length=200)),
                ('translate', models.CharField(blank=True, max_length=200)),
                ('last_picked', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
